language: php

php:
  - 5.5
  - 5.6
  - 7

env:
  - TYPO3_VERSION="^7.6.0"
  - TYPO3_VERSION="^8.6.0"
  - TYPO3_VERSION="dev-master"

matrix:
  exclude:
    - php: 5.5
      env: TYPO3_VERSION="^7.6.0"
    - php: 7
      env: TYPO3_VERSION="^7.6.0"
    - php: 7
      env: TYPO3_VERSION="^8.4.0"
    - php: 7
      env: TYPO3_VERSION="dev-master"

sudo: false

addons:
  apt:
    packages:
      - parallel
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    Build/bin/phpunit -c Build/UnitTests.xml
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
 